### ISSUE TITLE
URL encoding security issue

### ISSUE THREAD

**Issue by dsamarin** [ezzarghili/recaptcha-go#11]
Requests are built for the Google API with the following code:

https://github.com/ezzarghili/recaptcha-go/blob/fcf7f6a431eb9b7a43edc85065abb52c4c920e20/recaptcha.go#L71

What happens when the user appends his own secret? It seems necessary to investigate the possibility of malicious users messing with this. Why can't we use Golang's [url.Encode](https://golang.org/pkg/net/url/#Values.Encode)?

**Comment by ezzarghili** [comment]
Thank you for noticing that, that's valid security issue as this was assuming that the package user will sanitize the data received from the client and this may not be the case, I will get some time and fix this and release a fix release.
