### ISSUE TITLE
An option to use recaptcha.net

### ISSUE THREAD

**Issue by txfs19260817** [ezzarghili/recaptcha-go#22]
Hi, thanks for this great repo!
Is there any chance I could use  `recaptcha.net` instead of `www.google.com` to enable to use reCAPTCHA globally?
Thanks!

**Comment by ezzarghili** [comment]
Hi, thanks for your feedback.
recaptcha.net seems not to be reachable.

**Comment by ezzarghili** [comment]
Please open if you think I am missing something

**Comment by txfs19260817** [comment]
Thanks for your reply.
My bad, the url is `www.recaptcha.net` instead of recaptcha.net according to https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

>


    Yes, please use "www.recaptcha.net" in your code in circumstances when "www.google.com" is not accessible.

        First, replace <script src="https://www.google.com/recaptcha/api.js" async defer></script> with <script src="https://www.recaptcha.net/recaptcha/api.js" async defer></script>
        After that, apply the same to everywhere else that uses "www.google.com/recaptcha/" on your site.

**Comment by ezzarghili** [comment]
You can achieve that by providing a wrapper, as you can just update the public field `ReCAPTCHALink` in the `ReCAPTCHA` struct. 

Somthing like 

```go
recaptcha := NewReCAPTCHA(ReCAPTCHASecret, version, timeout)
recaptcha.reCAPTCHALink = "https://www.recaptcha.net/recaptcha/api/siteverify"
```

**Comment by montanaflynn** [comment]
Your example is referencing a non-existing field.

Just as a note for anyone finding this the library has one [unexported field `reCAPTCHALink`](https://github.com/ezzarghili/recaptcha-go/blob/master/recaptcha.go#L12) that is the default that's used for the struct field value but you can override it with the instance struct field:

```go
recaptcha := NewReCAPTCHA(ReCAPTCHASecret, version, timeout)
recaptcha.ReCAPTCHALink = "https://www.recaptcha.net/recaptcha/api/siteverify"
```

**Comment by ezzarghili** [comment]
Thanks, yes, obviously (or maybe not) that was a typo, a my comment states `you can just update the public field ReCAPTCHALink in the ReCAPTCHA struct.`.
I won't update my original comment snippet so your comment stays relevant :)
