### ISSUE TITLE
Threshold needs to be compared strictly

### ISSUE THREAD

**Issue by luza** [ezzarghili/recaptcha-go#23]
There is should be `>` instead of `>=` in threshold comparison.

Reference:
https://github.com/google/recaptcha/blob/master/src/ReCaptcha/ReCaptcha.php#L180

**Comment by ezzarghili** [comment]
Thank you for your feedback, this is a bit tricky.
I did not use the PHP library as reference, I used https://developers.google.com/recaptcha/docs/v3 
My reasoning for this is this part of the docs:
```
"score": number             // the score for this request (0.0 - 1.0)
```
~My expectation was that it was inclusive, but then it seems from my experience that the highest score seems always to be 0.9.~

I will fix this so people using other language implementations are not confused, I will need to bump a ~~major~~ minor release as this is a ~change in the API~

**Comment by luza** [comment]
Thank you.
