### ISSUE TITLE
DefaultTreshold typo

### ISSUE THREAD

**Issue by philip-firstorder** [ezzarghili/recaptcha-go#26]
DefaultTreshold typo appears 4 times, should be DefaultThreshold.

https://github.com/ezzarghili/recaptcha-go/blob/14b5e4c9097cdeec68186673c270e433946741c0/recaptcha.go#L22-L23

https://github.com/ezzarghili/recaptcha-go/blob/14b5e4c9097cdeec68186673c270e433946741c0/recaptcha.go#L167-L168

**Comment by ezzarghili** [comment]
Thanks for the report, actually 12 instances (Treshold) when including tests.
